baseurl = "/"
languageCode = "en-ca"
languageLang = "en"
title = "Port Hope HBIA"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/open-graph.jpg"]
eventsMainImage = "img/home.webp"
