backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "shop"
    label: "Shop"
    folder: "site/content/shop"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string", hint: "store name"}
      - {label: "Storefront", name: "storefront", widget: "image", required: false, hint: "image of the storefront"}
      - {label: "Inside", name: "inside", widget: "image", required: false, hint: "inside image of store"}
      - {label: "Body", name: "body", widget: "markdown", hint: "brief blurb about the store"}
      - {label: "Ontario Category", name: "ontario-category", widget: "select", hint: "business category for ontario government usage (not shown on shop pages)", options: ["Food, Beverage, Pharmacy", "Food Services", "Personal Services", "Professional Services", "Retail", "Other Services", "Vacant"]}
      - {label: "Business Type", name: "business-type", widget: "select", hint: "business type", options: ["Apparel", "Art Gallery", "Food & Pub", "Hotel", "Health & Fitness", "Home ware", "Professional Services", "Salon"]}
      - {label: "Latitude", name: "latitude", widget: "number", default: 43.95, min: 43.91, max: 43.97, step: 0.000001}
      - {label: "Longitude", name: "longitude", default: -78.29, min: -78.4, max: -78.1, step: 0.000001}
      - {label: "Vacant", name: "vacant", widget: "boolean", default: false, hint: "whether the store is vacant"}
      - {label: "Address", name: "address", widget: "string", hint: "one line about the address, e.g. 12 Walton Street"}
      - {label: "Phone", name: "phone", widget: "string", required: false, hint: "business phone number (public)"}
      - {label: "Website", name: "website", widget: "string", required: false, hint: "business website url"}
      - {label: "Facebook", name: "facebook", widget: "string", required: false, hint: "business facebook page url"}
      - {label: "Twitter", name: "twitter", widget: "string", required: false, hint: "business twitter page url"}
      - {label: "Instagram", name: "instagram", widget: "string", required: false, hint: "business instagram page url"}
      - {label: "Owner Name", name: "owner-name", widget: "string", required: false, hint: "owner name (private/for internal use)" }
      - {label: "Mailing List Email", name: "mailing-list", widget: "", required: false, hint: "mailing list email (private/for internal use)"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: text}
      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
