backend:
  name: git-gateway
  branch: main

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "event" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Event" # Used in the UI, ie.: "New Event"
    folder: "content/event" # The path to the folder where the documents are stored
    path: "{{slug}}/index" # Each document is inside a folder with the slug name.
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "directory"
    label: "Directory"
    folder: "content/directory"
    path: "{{slug}}/index"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Admin title. Use the address in the format 'john 21', 'Walton 57', etc. All streets except Walton must be lower case. Walton must be upper case. This affects sorting. Must be unique: use -a, -b, -c, etc if multiple businesses share the same address." }
      - { label: "Name", name: "name", widget: "string", hint: "Name on website. Use store name, or if vacant, residential, etc, put address" }
      - { label: "Slug", name: "slug", widget: "string", hint: "url for web page (lowercase, no spaces only dashes -)", pattern: [ "^[a-z0-9]+(?:[_-][a-z0-9]+)*$", "must be lowercase, without spaces. Dashes are allowed." ] }
      - { label: "Storefront", name: "storefront", widget: "image", required: false, hint: "image of the storefront, 600px x 600px; webp format. imageresizer.com" }
      - { label: "Other pictures", name: "otherPics", widget: "list", required: false, hint: "other images of store. 600px x 600px; webp format. imageresizer.com",  fields: [ { label: "Image", name: "image", widget: "image" } ] }
      - { label: "Body", name: "body", widget: "markdown", hint: "brief blurb about the store", required: false }
      - { label: "Ontario Category", name: "ontarioCategory", widget: "select", hint: "business category for ontario government usage (not shown on shop pages)", options: [ "Food, Beverage, Pharmacy", "Food Services", "Personal Services", "Professional Services", "Retail", "Other Services", "Vacant", "Residential" ] }
      - { label: "Business Type", name: "businessType", widget: "select", hint: "business type", options: [ "shop", "taste", "explore-stay", "service", "none" ] }
      - { label: "Latitude", name: "latitude", widget: "string", default: "43.95" }
      - { label: "Longitude", name: "longitude", widget: "string", default: "-78.29" }
      - { label: "Residential only", name: "residential", widget: "boolean", default: false, hint: "the property is residential only (not displayed on website)" }
      - { label: "Vacant", name: "vacant", widget: "boolean", default: false, hint: "whether the store is vacant (not displayed on website)" }
      - { label: "Address", name: "address", widget: "string", hint: "one line about the address, e.g. 12 Walton Street" }
      - { label: "Phone", name: "phone", widget: "string", required: false, hint: "business phone number (public)" }
      - { label: "Website", name: "website", widget: "string", required: false, hint: "business website url. Must start with https:// or http://" }
      - { label: "Facebook", name: "facebook", widget: "string", required: false, hint: "business facebook page url" }
      - { label: "Twitter", name: "twitter", widget: "string", required: false, hint: "business twitter page url" }
      - { label: "Instagram", name: "instagram", widget: "string", required: false, hint: "business instagram page url" }
      - { label: "Owner Name", name: "ownerName", widget: "string", required: false, hint: "owner name (private/for internal use)" }
      - { label: "Mailing List Email", name: "mailingList", widget: "", required: false, hint: "mailing list email (private/for internal use)" }
      - { label: "Building Owner Name", name: "buildingOwner", widget: "string", required: false, hint: "building owner name (private/for internal use)" }
      - { label: "Building Owner Mailing List Email", name: "buildingMailingList", widget: "", required: false, hint: "building owner mailing list email (private/for internal use)" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        editor:
          preview: false
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: "Welcome", name: welcome, widget: list, hint: "welcome in many different languages" }
          - { label: "Image Pop: intro", name: text, widget: list, hint: "words in the image pop section. Best with 10 items." }
          - { label: "Image pop: group 1 images", name: imagesGroup1, widget: list, fields: [
            { label: "Image", name: "image", widget: "image", hint: "250px in widest dimension; webp format" },
            { label: "Business name", name: "name", widget: "string" } ] }
          - { label: "Image pop: group 2 images", name: imagesGroup2, widget: list, fields: [
            { label: "Image", name: "image", widget: "image", hint: "250px wide; webp format" },
            { label: "Business name", name: "name", widget: "string", hint: "250px in widest dimension; webp format" } ] }
          - { label: "Image pop: group 3 images", name: imagesGroup3, widget: list, fields: [
            { label: "Image", name: "image", widget: "image", hint: "250px in widest dimension; webp format" },
            { label: "Business name", name: "name", widget: "string" } ] }
          - { label: "Image pop: group 4 images", name: imagesGroup4, widget: list, fields: [
            { label: "Image", name: "image", widget: "image", hint: "250px in widest dimension; webp format" },
            { label: "Business name", name: "name", widget: "string" } ] }
          - { label: Meta, name: meta, widget: string, hint: "SEO description for search engines. Should be under 160 characters" }
      - file: "content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Intro, name: intro, widget: object, fields: [ { label: Heading, name: heading, widget: string }, { label: Description, name: description, widget: text }, { label: Blurbs, name: blurbs, widget: list, fields: [ { label: Image, name: image, widget: image }, { label: Text, name: text, widget: text } ] } ] }
          - { label: Main, name: main, widget: object, fields: [ { label: Heading, name: heading, widget: string }, { label: Description, name: description, widget: text }, { label: Image1, name: image1, widget: object, fields: [ { label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string } ] }, { label: Image2, name: image2, widget: object, fields: [ { label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string } ] }, { label: Image3, name: image3, widget: object, fields: [ { label: Image, name: image, widget: image }, { label: Alt, name: alt, widget: string } ] } ] }
          - { label: Testimonials, name: testimonials, widget: list, fields: [ { label: Quote, name: quote, widget: string }, { label: Author, name: author, widget: string } ] }
          - { label: Full_image, name: full_image, widget: image }
          - { label: Pricing, name: pricing, widget: object, fields: [ { label: Heading, name: heading, widget: string }, { label: Description, name: description, widget: string }, { label: Plans, name: plans, widget: list, fields: [ { label: Plan, name: plan, widget: string }, { label: Price, name: price, widget: string }, { label: Description, name: description, widget: string }, { label: Items, name: items, widget: list } ] } ] }
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "data/footer.json"
        label: Footer
        name: footer
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Blurb, name: blurb, widget: text }
      - file: "hugo.toml"
        label: Site Config
        name: config
        editor:
          preview: false
        fields:
          - { label: Site Title for Browser Tab, name: title, widget: string }
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
